# Generated by Django 4.1.2 on 2022-12-05 04:32

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("django_drf_todo_list", "0002_alter_todo_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(
                blank=True,
                db_column="created_db_column",
                db_index=True,
                db_tablespace="created_db_tablespace",
                default=django.utils.timezone.now,
                help_text='<small class="text-muted">DateTimeField</small><hr><br>',
                null=True,
                verbose_name="Дата и время создания",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(
                blank=True,
                db_column="description_db_column",
                db_index=True,
                db_tablespace="description_db_tablespace",
                default="",
                help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>',
                max_length=3000,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(0),
                    django.core.validators.MaxLengthValidator(3000),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(
                blank=True,
                db_column="is_completed_db_column",
                db_index=True,
                db_tablespace="is_completed_db_tablespace",
                default=False,
                help_text='<small class="text-muted">BooleanField</small><hr><br>',
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(
                blank=True,
                db_column="title_db_column",
                db_index=True,
                db_tablespace="title_db_tablespace",
                default="",
                help_text='<small class="text-muted">CharField [0, 300]</small><hr><br>',
                max_length=300,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(0),
                    django.core.validators.MaxLengthValidator(300),
                ],
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated",
            field=models.DateTimeField(
                blank=True,
                db_column="updated_db_column",
                db_index=True,
                db_tablespace="updated_db_tablespace",
                default=django.utils.timezone.now,
                help_text='<small class="text-muted">DateTimeField</small><hr><br>',
                null=True,
                verbose_name="Дата и время обновления",
            ),
        ),
    ]
