# Generated by Django 4.1.2 on 2022-11-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_drf_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
