# Generated by Django 4.1.2 on 2022-10-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_resultlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultlist',
            options={'ordering': ('-updated', 'created'), 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
    ]
