# Generated by Django 4.1.2 on 2022-10-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_resultlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultlist',
            options={'ordering': ('-updated', 'created'), 'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
    ]
