# Generated by Django 4.1.2 on 2022-11-04 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_usermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggingmodel',
            name='error',
        ),
        migrations.AddField(
            model_name='loggingmodel',
            name='text',
            field=models.TextField(blank=True, db_column='text_db_column', db_index=True, db_tablespace='text_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(3000)], verbose_name='Текст ошибки/исключения/ответа'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('logging_action', 'Логирование действий в базу ("logging_action=True/False")'), ('print_action', 'Вывод в консоль действий ("print_action=True/False")'), ('logging_error', 'Логирование ошибок в базу ("logging_error=True/False")'), ('print_error', 'Вывод в консоль ошибок ("print_error=True/False")'), ('logging_response', 'Логирование ответов в базу ("logging_response=True/False")'), ('print_response', 'Вывод в консоль ответов ("print_response=True/False")'), ('scheduler_personal', 'Планировщик обновления персонала из 1С'), ('scheduler_superuser', 'Планировщик создания стандартных суперпользователей'), ('scheduler_group', 'Планировщик создания стандартных групп')], db_index=True, default='', help_text='<small class="text-muted">CharField [0, 300]</small><hr><br>', max_length=300, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(300)], verbose_name='Тип'),
        ),
    ]
