# Generated by Django 4.1.2 on 2022-11-11 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_remove_loggingmodel_error_loggingmodel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodel',
            name='token',
            field=models.CharField(blank=True, db_column='token_db_column', db_index=True, db_tablespace='token_db_tablespace', default='', error_messages=False, help_text='<small class="text-muted">SlugField [0, 150]</small><hr><br>', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(150)], verbose_name='Токен'),
        ),
    ]
